### ISSUE TITLE
Using PHPCS in the ant-build-file

### ISSUE THREAD

**Issue by Eternal-Infinity** [sebastianbergmann/php-jenkins-template#104]
Hey there,

I don't know if this is the right place for this question.

My problem ist the following:
I use Windows 7, have a application that I want to use the jenkins-template with.
So I did what is in the tutorial on http://jenkins-php.org.
I created a build.xml in my application, telling Apache Ant what PHP-Tool to use.
Now comes the problem I have.
All the tools work well (phploc, pdepend, phpmd,....), but when it comes to the CodeSniffer, it seems that the ruleset.xml is not considered here.

My example:
All the tools are here:
C:\Program Files\PHPTools
My application lies here (including the build.xml): 
C:\web\myApplication
In this path is also a Sniffs-folder, where my custom sniffs go.
The build.xml looks like this:
```
[...]
<target name="phpcs-ci"
         depends="prepare"
         description="Find coding standard violations using PHP_CodeSniffer and log result in XML format. Intended for usage within a continuous integration environment.">
  <exec executable="${toolsdir}phpcs.bat">
   <arg value="--report=checkstyle" />
   <arg value="--report-file=${basedir}/build/logs/checkstyle.xml" />
   <arg value="--standard=${basedir}/build/Sniffs/myCustomSniffs" />
   <arg value="--extensions=php" />
   <arg value="--ignore=autoload.php" />
   <arg path="${basedir}/src" />
  </exec>
 </target>
[...]
```
All the Sniffs in "myCustomSniffs" are being executed, BUT I have a ruleset.xml in that folder, saying that only a few Sniffs in that folder shall be executed, along with some other sniffs from other folders (like "Generic.PHP.DeprecatedFunctions").
Also, I tried that in the phpcs.xml in the build-folder of my application, like the tutorial says.
This seems to not be considered as well, no matter what I write in the phpcs.xml, it does nothing more or less.
Am I missing something?
HELP!! :-)

Oh, and if this is not the right place to ask this, please don't kill me ;-)

**Comment by sebastianbergmann** [comment]
Please ask questions to PHP_CodeSniffer at the appropriate place.
