### ISSUE TITLE
On the dashboard of a job the test result trend chart is shown twice

### ISSUE THREAD

**Issue by pietervogelaar** [sebastianbergmann/php-jenkins-template#105]
The php jenkins template works very well in Jenkins. Although I have one minor issue.
On the dashboard of a job the test result trend chart is shown twice. Also the "Latest Test Result" link with its icon is displayed twice.

Is there a bug somewhere or can I set something right?

**Comment by sebastianbergmann** [comment]
Does this problem persist? Can you attach a screenshot? Thanks!
