### ISSUE TITLE
Broken link on website

### ISSUE THREAD

**Issue by afilina** [sebastianbergmann/php-jenkins-template#114]
The installation page (http://jenkins-php.org/installation.html) has a link that points to PHP_CodeSniffer is the one from PEAR, which no longer exists. Since there are discussions to pull the plug on PEAR anyway, I recommend that the link points instead to https://github.com/squizlabs/PHP_CodeSniffer. This makes it more convenient to install all the dependencies using Composer, rather than hunting down each one using a different tool.

**Comment by thorsten** [comment]
+1
