### ISSUE TITLE
Can't accomplish build with Jenkins, Symfony3 and PHPUnit 5.3

### ISSUE THREAD

**Issue by bamper** [sebastianbergmann/php-jenkins-template#123]
Hello, 

Trying to learn CI, I got stuck with the following problem:
Ant in command-line gives 'BUILD SUCCESSFUL' message.
When I push code to GitHub and run Jenkins on AWS, evth pass except PHPUnit part error:

> phpunit:
  [phpunit] PHP Warning:  require(/var/lib/jenkins/workspace/mavajob/app/../vendor/autoload.php): failed to open stream: No such file or directory in /var/lib/jenkins/workspace/mavajob/app/autoload.php on line 9
  [phpunit] PHP Stack trace:
  [phpunit] PHP   1. {main}() /usr/bin/phpunit:0
  [phpunit] PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:29
  [phpunit] PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:106
  [phpunit] PHP   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:117
  [phpunit] PHP   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:622
  [phpunit] PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:793
  [phpunit] PHP   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:38
  [phpunit] PHP   8. include_once() /usr/share/php/PHPUnit/Util/Fileloader.php:56
  [phpunit] PHP Fatal error:  require(): Failed opening required '/var/lib/jenkins/workspace/mavajob/app/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/lib/jenkins/workspace/mavajob/app/autoload.php on line 9
  [phpunit] PHP Stack trace:
  [phpunit] PHP   1. {main}() /usr/bin/phpunit:0
  [phpunit] PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:29
  [phpunit] PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:106
  [phpunit] PHP   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:117
  [phpunit] PHP   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:622
  [phpunit] PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:793
  [phpunit] PHP   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:38
  [phpunit] PHP   8. include_once() /usr/share/php/PHPUnit/Util/Fileloader.php:56
  [phpunit] Result: 255

phpunit part from build.xml
```xml
    <target name="phpunit"
        unless="phpunit.done"
        depends="prepare"
        description="Run unit tests with PHPUnit">
        <exec executable="${phpunit}" resultproperty="result.phpunit" taskname="phpunit">
            <arg value="--configuration"/>
            <arg path="${basedir}/phpunit.xml"/>
        </exec>
        <property name="phpunit.done" value="true"/>
    </target>
```
phpunit.xml
```xml
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/4.1/phpunit.xsd"
         backupGlobals="false"
         backupStaticAttributes="false"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false"
         syntaxCheck="false"
         bootstrap="app/autoload.php"
>
    <php>
        <ini name="error_reporting" value="-1" />
        <server name="KERNEL_DIR" value="app/" />
    </php>

    <testsuites>
        <testsuite name="Project Test Suite">
            <directory>tests</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist>
            <directory>src</directory>
            <exclude>
                <directory>src/*Bundle/Resources</directory>
                <directory>src/*/*Bundle/Resources</directory>
                <directory>src/*/Bundle/*Bundle/Resources</directory>
            </exclude>
        </whitelist>
    </filter>
</phpunit>
```

**Comment by bamper** [comment]
Solved, I forgot to add composer target.

**Comment by anchan42** [comment]
I have got the same problem. Could you be a bit more specific on how was the problem resolved?
