### ISSUE TITLE
How to run a command to specify a different version of the project, respectively php

### ISSUE THREAD

**Issue by xiaoxing598** [sebastianbergmann/php-jenkins-template#125]
I now have a number of projects to be analyzed, and there are php5.3 php5.6 when the projects are deployed to jenkins, I found the system default only to find /usr/bin/php, I now want to specify the path to php , what to do?

**Comment by sebastianbergmann** [comment]
This is outside the scope of this project. This project provides a *template* that can, and should, be customized to meet individual requirements.
