### ISSUE TITLE
Missing resultproperty in the phpunit-no-coverage target of the Ant build

### ISSUE THREAD

**Issue by craig-davis** [sebastianbergmann/php-jenkins-template#126]
The `phpunit-no-coverage` task in the Ant build is missing the `resultproperty` and using this task in a build will result in a failure if the `-check-failure` target is subsequently called.

Is there a place where I can submit a PR for this?

**Comment by sebastianbergmann** [comment]
Sorry for taking so long to respond.

The right place for pull requests is in fact this repository. On the [gh-pages](https://github.com/sebastianbergmann/php-jenkins-template/tree/gh-pages) branch you find the website that is hosted on http://jenkins-php.org/.
