### ISSUE TITLE
third party code is separated

### ISSUE THREAD

**Issue by subbu6502** [sebastianbergmann/php-jenkins-template#129]
Hai,

I have created a project using this template and it has third party code that is separated from source. the third party code placed in "plugins" folder and it also has "vendor" composer folder.

PHPUNIT not recognising this folder "plugins" and "plugins/vendor/autoload.php" even I added composer to Ant script.

How to fix it.

Thanks

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
