### ISSUE TITLE
Investigate Warnings plugin

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-jenkins-template#41]
The [Warnings plugin](http://wiki.jenkins-ci.org/display/JENKINS/Warnings+Plugin) looks interesting (and has PHP support).

**Comment by SchulteMarkus** [comment]
I just wanted to add the proposal here, to add [Warnings Plugin](http://wiki.jenkins-ci.org/display/JENKINS/Warnings+Plugin) to the php-jenkins-template. When I setup a new jenkins-php-project using php-jenkins-template, it is common to me to add  [Warnings Plugin](http://wiki.jenkins-ci.org/display/JENKINS/Warnings+Plugin) with enabled PHP-support afterwards.
